/// <reference types="vite/client" />

/** generated by vite-plugin-runtime */
interface ImportMetaEnv {
  readonly REACT_APP_TELEGRAM_BOT_TOKEN: string;
  readonly DATABASE_URL: string;
  readonly HELIUS_API: string;
  readonly SYNDICA_API: string;
  readonly SYNDICA_API_KEY: string;
}
interface ImportMeta {
  readonly env: ImportMetaEnv;
}
